/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign1;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum cab_style {
  Crew, Extended, Regular  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"cab_style\",\"namespace\":\"com.refactorlabs.cs378.assign1\",\"symbols\":[\"Crew\",\"Extended\",\"Regular\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
